name: Release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build -t lm-logs-fluentd .
    - name: Start container
      run: id=$(docker create lm-logs-fluentd) && docker cp $id:/logicmonitor/release.gem .
    - name: Create directory for credentials
      run: mkdir ~/.gem && touch ~/.gem/credentials
    - name: Add credentials
      env:
        GEM_ACCOUNT_PASSWORD: ${{ secrets.GEM_ACCOUNT_PASSWORD }}
      run: curl -u LogicMonitor:$GEM_ACCOUNT_PASSWORD https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials && chmod 0600 ~/.gem/credentials
    - name: Gem push
      run: gem push release.gem
      